### ISSUE TITLE
How to make it work with GDM?

### ISSUE THREAD

**Issue by mansoorahmedme** [skarnet/s6-rc#2]
How can I make it work with GDM.

I have installed `gdm` and `gdm-s6` and enabled the service via:

`s6-rc-bundle-update add default gdm`.

After the boot is finished, I get a blank screen.

**Comment by mansoorahmedme** [comment]
Update:

Don't know why don't know how but, GDM works now. But now Network manager and Bluetoothd are not working.

**Comment by skarnet** [comment]
Neither `gdm`, `gdm-s6`, nor `s6-rc-bundle-update` are tools provided by the original s6 or s6-rc packages. For distribution-specific tools, your distribution is the place to ask for support.
